identifier: cidr.amaru8.adaptiveaccentseverywhere
name: Adaptive Accents Everywhere
description: Changes the accent color of the app based on the playing song's album cover.
author: amaru8
repo: https://github.com/Amaru8/Cider-AdaptiveAccentsEverywhere
entry:
    'plugin.js':
        type: main
